name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: "weatherbot"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}
            ADMIN_TELEGRAM_ID=${{ secrets.ADMIN_TELEGRAM_ID }}
            EXCHANGE_API_KEY=${{ secrets.EXCHANGE_API_KEY }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          envs: DOCKER_HUB_USERNAME,IMAGE_NAME,GITHUB_SHA
          script: |
            # Pull the new image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            # Stop and remove the old container if it exists
            docker stop weatherbot || true
            docker rm weatherbot || true
            
            # Run the new container
            docker run -d \
              --name weatherbot \
              --restart always \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              -e OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }} \
              -e ADMIN_TELEGRAM_ID=${{ secrets.ADMIN_TELEGRAM_ID }} \
              -e EXCHANGE_API_KEY=${{ secrets.EXCHANGE_API_KEY }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
